### ISSUE TITLE
More pictures of electronics?

### ISSUE THREAD

**Issue by zmrow** [pjnovas/weather-station#1]
Any chance you have more pictures of the board you put together?  I'd like to see the back side of the board to get a better idea of your wire routing, etc.

Great project btw!

Thanks!

**Comment by pjnovas** [comment]
hey I gave it away as a gift so I don't have it any more but I may see the person who has it this Sunday, if so I'll take a pic of it and came back to this issue.

**Comment by pjnovas** [comment]
So, here are some more pics, hope it helps

![20180527_160636](https://user-images.githubusercontent.com/712927/40660525-9fef7504-6327-11e8-8337-e38cc78a2d4f.jpg)
![20180527_160719](https://user-images.githubusercontent.com/712927/40660526-a016bf4c-6327-11e8-9cd2-973e4a6c7178.jpg)
![20180527_160820](https://user-images.githubusercontent.com/712927/40660527-a040c4ae-6327-11e8-8a7f-c9f70d674c92.jpg)
![20180527_160845](https://user-images.githubusercontent.com/712927/40660529-a0725834-6327-11e8-9174-f5ab6155f851.jpg)

**Comment by zmrow** [comment]
Thanks!!
